services:
  node-app:
    container_name: my-app-container
    ports: 
      - "4000:4000"  
    env_file:
      - ./.env
    depends_on: 
      - postgrs  
      - redis       
  # mongo:
  #   image: mongo
  #   restart: always
  #   volumes:
  #     - mongo-db:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example

  postgrs:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
     - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: root

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #     ME_CONFIG_BASICAUTH_ENABLED: true
  #     ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
  #     ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
  #   depends_on: 
  #     - mongo  

  redis: 
    image: redis    


  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf    
    ports:
      - "80:80"
    depends_on: 
      - node-app  
  




      
volumes:
  mongo-db: 
  postgres-db:

